services:
  date:
    build:
      context: ./date-service
      dockerfile: Dockerfile
    container_name: date-service

  result:
    build:
      context: ./result-service
      dockerfile: Dockerfile
    container_name: result-service
    env_file:
      - .env
    depends_on:
      - date

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "5000:80"

    volumes:
      - ./result-service/static:/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - result
